### PR TITLE
Use clock and perf_counter rather than time and monotonic

### PR DESCRIPTION
**Pull request by clayote**
These seem more appropriate for the purpose according to the documentation.

perf_counter is guaranteed to keep ticking during sleep, which might include timeouts while we are waiting for subprocesses to finish.

clock doesn't exactly have guarantees like that but claims to be "the function to use for benchmarking Python or timing algorithms."

I'm not actually using monotonic anymore so the branch name is incorrect, oh well

### CODE REVIEW

**Comment by clayote** [comment]
This last commit also fixes the summary reporter just in general.

**Comment by xrg** [comment]
May we squash those commits? After all, they leave just a few lines changed..

**Comment by xrg** [comment]
Oops, on a second glance, `clock()` is NOT what we want. It tracks *processor* time, that is, the amount of CPU time used by this process. Advances slower than real time, sometimes (on heavy I/O) small fraction of the elapsed `time()` .

So, please, can we stay with `monotonic()` + `time()` fallback for measuring elapsed time?

I understand that sometimes we want to measure CPU "burnt" during some test, not necessarily the real time that includes any other factor slowing the system down. But that would be an exception, not the rule.

**Comment by clayote** [comment]
Fair enough

**Pull request closed without merging**
